import os
import codecs

def writeFile(File, name, lang):

  wekaFile=open(os.path.join(os.path.join("C:/Users/ameer15/python-code/working-function",name),"age15"+name+".arff"),'a+')

  wekaFile.write("@relation \"age\" ")
  wekaFile.write("\n")
  
  
  
  if lang == "en":
	#wekaFile.write("@attribute percentageOfQuesSen numeric")
	#wekaFile.write("\n")
	#wekaFile.write("@attribute percentageOfShortSen numeric")
	#wekaFile.write("\n")
	#wekaFile.write("@attribute percentageOfLongSen numeric ")
	#wekaFile.write("\n") 
	#wekaFile.write("@attribute averageSenLength numeric ") 
	#wekaFile.write("\n") 
	wekaFile.write("@attribute avgWordLength numeric ")
	wekaFile.write("\n")
	wekaFile.write("@attribute percentageOfWordsWithSixAndMoreLetters    numeric ")
	wekaFile.write("\n")
	wekaFile.write("@attribute percentageOfWordsWithTwoAndThreeLetters   numeric ") 
	wekaFile.write("\n")
	#wekaFile.write("@attribute percentageOfSemicolons   numeric ") 
	#wekaFile.write("\n")
	#wekaFile.write("@attribute percentageOfPunctuations  numeric ") 
	#wekaFile.write("\n")
	wekaFile.write("@attribute percentageOfPronouns  numeric ") 
	wekaFile.write("\n")
	#wekaFile.write("@attribute percentageOfPrepositions  numeric ") 
	#wekaFile.write("\n")
	#wekaFile.write("@attribute percentageOfCoordinatingConjunction  numeric ") 
	#wekaFile.write("\n")
	#wekaFile.write("@attribute percentageOfComma numeric ") 
	#wekaFile.write("\n")
	#wekaFile.write("@attribute percentageOfArticles numeric ") 
	#wekaFile.write("\n")
	#wekaFile.write("@attribute percentageOfWordsWithOneSyllables numeric ") 
	#wekaFile.write("\n")
	wekaFile.write("@attribute percentageOfWordsWithThreePlusSyllable numeric ") 
	wekaFile.write("\n")
	wekaFile.write("@attribute averageSyllablePerWords numeric ") 
	wekaFile.write("\n")
	#wekaFile.write("@attribute percentageOfAdj numeric ") 
	#wekaFile.write("\n")
	#wekaFile.write("@attribute percentageOfAdverb numeric ") 
	#wekaFile.write("\n")
	#wekaFile.write("@attribute ercentageOfCapital numeric ") 
	#wekaFile.write("\n")
	wekaFile.write("@attribute percentageOfColons numeric ") 
	wekaFile.write("\n")
	#wekaFile.write("@attribute percentageOfDet numeric ") 
	#wekaFile.write("\n")
	wekaFile.write("@attribute percentageOfDigits numeric ") 
	wekaFile.write("\n")
	wekaFile.write("@attribute percentageOfFullStops numeric ") 
	wekaFile.write("\n")
	#wekaFile.write("@attribute percentageOfInterjections numeric ") 
	#wekaFile.write("\n")
	#wekaFile.write("@attribute percentageOfModal numeric ") 
	#wekaFile.write("\n")
	#wekaFile.write("@attribute percentageOfNouns numeric ") 
	#wekaFile.write("\n")
	wekaFile.write("@attribute percentageOfPersonalPronouns numeric ") 
	wekaFile.write("\n")
	#wekaFile.write("@attribute percentageOfVerbs numeric ") 
	#wekaFile.write("\n")
	wekaFile.write("@attribute class? {18-24, 25-34, 35-49, 50-XX, XX-XX}  ") 
	wekaFile.write("\n")
	wekaFile.write("\n")
	wekaFile.write("@data")
	wekaFile.write("\n")

	f=open(os.path.join("C:/Users/ameer15/python-code/working-function",File+".txt"),'r')
	text=f.read()
	lines=text.split()

	for line in lines:
		w=line.split(',')
		#for i in range(0,29):
			#wekaFile.write(str(w[i]))
			#wekaFile.write(",")
		wekaFile.write(str(w[4]))
		wekaFile.write(",")
		wekaFile.write(str(w[5]))
		wekaFile.write(",")
		wekaFile.write(str(w[6]))
		wekaFile.write(",")
		wekaFile.write(str(w[9]))
		wekaFile.write(",")
		wekaFile.write(str(w[15]))
		wekaFile.write(",")
		wekaFile.write(str(w[16]))
		wekaFile.write(",")
		wekaFile.write(str(w[20]))
		wekaFile.write(",")
		wekaFile.write(str(w[22]))
		wekaFile.write(",")
		wekaFile.write(str(w[23]))
		wekaFile.write(",")
		wekaFile.write(str(w[27]))
		wekaFile.write(",")
		#wekaFile.write(str(w[30]))
		wekaFile.write("?")
		wekaFile.write("\n")                 
  
	wekaFile.close()
	f.close()
  
  
  elif lang == "it":
	#wekaFile.write("@attribute percentageOfQuesSen numeric")
	#wekaFile.write("\n")
	#wekaFile.write("@attribute percentageOfShortSen numeric")
	#wekaFile.write("\n")
	#wekaFile.write("@attribute percentageOfLongSen numeric ")
	#wekaFile.write("\n") 
	#wekaFile.write("@attribute averageSenLength numeric ") 
	#wekaFile.write("\n") 
	wekaFile.write("@attribute avgWordLength numeric ")
	wekaFile.write("\n")
	wekaFile.write("@attribute percentageOfWordsWithSixAndMoreLetters    numeric ")
	wekaFile.write("\n")
	wekaFile.write("@attribute percentageOfWordsWithTwoAndThreeLetters   numeric ") 
	wekaFile.write("\n")
	#wekaFile.write("@attribute percentageOfSemicolons   numeric ") 
	#wekaFile.write("\n")
	#wekaFile.write("@attribute percentageOfPunctuations  numeric ") 
	#wekaFile.write("\n")
	wekaFile.write("@attribute percentageOfPronouns  numeric ") 
	wekaFile.write("\n")
	#wekaFile.write("@attribute percentageOfPrepositions  numeric ") 
	#wekaFile.write("\n")
	#wekaFile.write("@attribute percentageOfCoordinatingConjunction  numeric ") 
	#wekaFile.write("\n")
	#wekaFile.write("@attribute percentageOfComma numeric ") 
	#wekaFile.write("\n")
	#wekaFile.write("@attribute percentageOfArticles numeric ") 
	#wekaFile.write("\n")
	#wekaFile.write("@attribute percentageOfWordsWithOneSyllables numeric ") 
	#wekaFile.write("\n")
	wekaFile.write("@attribute percentageOfWordsWithThreePlusSyllable numeric ") 
	wekaFile.write("\n")
	wekaFile.write("@attribute averageSyllablePerWords numeric ") 
	wekaFile.write("\n")
	#wekaFile.write("@attribute percentageOfAdj numeric ") 
	#wekaFile.write("\n")
	#wekaFile.write("@attribute percentageOfAdverb numeric ") 
	#wekaFile.write("\n")
	#wekaFile.write("@attribute ercentageOfCapital numeric ") 
	#wekaFile.write("\n")
	wekaFile.write("@attribute percentageOfColons numeric ") 
	wekaFile.write("\n")
	#wekaFile.write("@attribute percentageOfDet numeric ") 
	#wekaFile.write("\n")
	wekaFile.write("@attribute percentageOfDigits numeric ") 
	wekaFile.write("\n")
	wekaFile.write("@attribute percentageOfFullStops numeric ") 
	wekaFile.write("\n")
	#wekaFile.write("@attribute percentageOfInterjections numeric ") 
	#wekaFile.write("\n")
	#wekaFile.write("@attribute percentageOfModal numeric ") 
	#wekaFile.write("\n")
	#wekaFile.write("@attribute percentageOfNouns numeric ") 
	#wekaFile.write("\n")
	wekaFile.write("@attribute percentageOfPersonalPronouns numeric ") 
	wekaFile.write("\n")
	#wekaFile.write("@attribute percentageOfVerbs numeric ") 
	#wekaFile.write("\n")
	wekaFile.write("@attribute class? {18-24, 25-34, 35-49, 50-XX, XX-XX}  ") 
	wekaFile.write("\n")
	wekaFile.write("\n")
	wekaFile.write("@data")
	wekaFile.write("\n")

	f=open(os.path.join("C:/Users/ameer15/python-code/working-function",File+".txt"),'r')
	text=f.read()
	lines=text.split()

	for line in lines:
		w=line.split(',')
		#for i in range(0,29):
			#wekaFile.write(str(w[i]))
			#wekaFile.write(",")
		wekaFile.write(str(w[4]))
		wekaFile.write(",")
		wekaFile.write(str(w[5]))
		wekaFile.write(",")
		wekaFile.write(str(w[6]))
		wekaFile.write(",")
		wekaFile.write(str(w[9]))
		wekaFile.write(",")
		wekaFile.write(str(w[15]))
		wekaFile.write(",")
		wekaFile.write(str(w[16]))
		wekaFile.write(",")
		wekaFile.write(str(w[20]))
		wekaFile.write(",")
		wekaFile.write(str(w[22]))
		wekaFile.write(",")
		wekaFile.write(str(w[23]))
		wekaFile.write(",")
		wekaFile.write(str(w[27]))
		wekaFile.write(",")
		wekaFile.write("?")
		#wekaFile.write(str(w[30])
		wekaFile.write("\n")                 
  
	wekaFile.close()
	f.close()
  
  
  
  
  elif lang == "nl":
	#wekaFile.write("@attribute percentageOfQuesSen numeric")
	#wekaFile.write("\n")
	#wekaFile.write("@attribute percentageOfShortSen numeric")
	#wekaFile.write("\n")
	#wekaFile.write("@attribute percentageOfLongSen numeric ")
	#wekaFile.write("\n") 
	#wekaFile.write("@attribute averageSenLength numeric ") 
	#wekaFile.write("\n") 
	wekaFile.write("@attribute avgWordLength numeric ")
	wekaFile.write("\n")
	wekaFile.write("@attribute percentageOfWordsWithSixAndMoreLetters    numeric ")
	wekaFile.write("\n")
	wekaFile.write("@attribute percentageOfWordsWithTwoAndThreeLetters   numeric ") 
	wekaFile.write("\n")
	#wekaFile.write("@attribute percentageOfSemicolons   numeric ") 
	#wekaFile.write("\n")
	#wekaFile.write("@attribute percentageOfPunctuations  numeric ") 
	#wekaFile.write("\n")
	wekaFile.write("@attribute percentageOfPronouns  numeric ") 
	wekaFile.write("\n")
	#wekaFile.write("@attribute percentageOfPrepositions  numeric ") 
	#wekaFile.write("\n")
	#wekaFile.write("@attribute percentageOfCoordinatingConjunction  numeric ") 
	#wekaFile.write("\n")
	#wekaFile.write("@attribute percentageOfComma numeric ") 
	#wekaFile.write("\n")
	#wekaFile.write("@attribute percentageOfArticles numeric ") 
	#wekaFile.write("\n")
	#wekaFile.write("@attribute percentageOfWordsWithOneSyllables numeric ") 
	#wekaFile.write("\n")
	wekaFile.write("@attribute percentageOfWordsWithThreePlusSyllable numeric ") 
	wekaFile.write("\n")
	wekaFile.write("@attribute averageSyllablePerWords numeric ") 
	wekaFile.write("\n")
	#wekaFile.write("@attribute percentageOfAdj numeric ") 
	#wekaFile.write("\n")
	#wekaFile.write("@attribute percentageOfAdverb numeric ") 
	#wekaFile.write("\n")
	#wekaFile.write("@attribute ercentageOfCapital numeric ") 
	#wekaFile.write("\n")
	wekaFile.write("@attribute percentageOfColons numeric ") 
	wekaFile.write("\n")
	#wekaFile.write("@attribute percentageOfDet numeric ") 
	#wekaFile.write("\n")
	wekaFile.write("@attribute percentageOfDigits numeric ") 
	wekaFile.write("\n")
	wekaFile.write("@attribute percentageOfFullStops numeric ") 
	wekaFile.write("\n")
	#wekaFile.write("@attribute percentageOfInterjections numeric ") 
	#wekaFile.write("\n")
	#wekaFile.write("@attribute percentageOfModal numeric ") 
	#wekaFile.write("\n")
	#wekaFile.write("@attribute percentageOfNouns numeric ") 
	#wekaFile.write("\n")
	wekaFile.write("@attribute percentageOfPersonalPronouns numeric ") 
	wekaFile.write("\n")
	#wekaFile.write("@attribute percentageOfVerbs numeric ") 
	#wekaFile.write("\n")
	wekaFile.write("@attribute class? {18-24, 25-34, 35-49, 50-XX, XX-XX}  ") 
	wekaFile.write("\n")
	wekaFile.write("\n")
	wekaFile.write("@data")
	wekaFile.write("\n")

	f=open(os.path.join("C:/Users/ameer15/python-code/working-function",File+".txt"),'r')
	text=f.read()
	lines=text.split()

	for line in lines:
		w=line.split(',')
		#for i in range(0,29):
			#wekaFile.write(str(w[i]))
			#wekaFile.write(",")
		wekaFile.write(str(w[4]))
		wekaFile.write(",")
		wekaFile.write(str(w[5]))
		wekaFile.write(",")
		wekaFile.write(str(w[6]))
		wekaFile.write(",")
		wekaFile.write(str(w[9]))
		wekaFile.write(",")
		wekaFile.write(str(w[15]))
		wekaFile.write(",")
		wekaFile.write(str(w[16]))
		wekaFile.write(",")
		wekaFile.write(str(w[20]))
		wekaFile.write(",")
		wekaFile.write(str(w[22]))
		wekaFile.write(",")
		wekaFile.write(str(w[23]))
		wekaFile.write(",")
		wekaFile.write(str(w[27]))
		wekaFile.write(",")
		wekaFile.write("?")
		#wekaFile.write(str(w[30]))
		wekaFile.write("\n")                 
  
	wekaFile.close()
	f.close()
  
  
  elif lang == "es":
	#wekaFile.write("@attribute percentageOfQuesSen numeric")
	#wekaFile.write("\n")
	#wekaFile.write("@attribute percentageOfShortSen numeric")
	#wekaFile.write("\n")
	#wekaFile.write("@attribute percentageOfLongSen numeric ")
	#wekaFile.write("\n") 
	wekaFile.write("@attribute averageSenLength numeric ") 
	wekaFile.write("\n") 
	wekaFile.write("@attribute avgWordLength numeric ")
	wekaFile.write("\n")
	wekaFile.write("@attribute percentageOfWordsWithSixAndMoreLetters    numeric ")
	wekaFile.write("\n")
	wekaFile.write("@attribute percentageOfWordsWithTwoAndThreeLetters   numeric ") 
	wekaFile.write("\n")
	#wekaFile.write("@attribute percentageOfSemicolons   numeric ") 
	#wekaFile.write("\n")
	#wekaFile.write("@attribute percentageOfPunctuations  numeric ") 
	#wekaFile.write("\n")
	#wekaFile.write("@attribute percentageOfPronouns  numeric ") 
	#wekaFile.write("\n")
	#wekaFile.write("@attribute percentageOfPrepositions  numeric ") 
	#wekaFile.write("\n")
	#wekaFile.write("@attribute percentageOfCoordinatingConjunction  numeric ") 
	#wekaFile.write("\n")
	#wekaFile.write("@attribute percentageOfComma numeric ") 
	#wekaFile.write("\n")
	#wekaFile.write("@attribute percentageOfArticles numeric ") 
	#wekaFile.write("\n")
	#wekaFile.write("@attribute percentageOfWordsWithOneSyllables numeric ") 
	#wekaFile.write("\n")
	#wekaFile.write("@attribute percentageOfWordsWithThreePlusSyllable numeric ") 
	#wekaFile.write("\n")
	#wekaFile.write("@attribute averageSyllablePerWords numeric ") 
	#wekaFile.write("\n")
	#wekaFile.write("@attribute percentageOfAdj numeric ") 
	#wekaFile.write("\n")
	#wekaFile.write("@attribute percentageOfAdverb numeric ") 
	#wekaFile.write("\n")
	#wekaFile.write("@attribute ercentageOfCapital numeric ") 
	#wekaFile.write("\n")
	#wekaFile.write("@attribute percentageOfColons numeric ") 
	#wekaFile.write("\n")
	#wekaFile.write("@attribute percentageOfDet numeric ") 
	#wekaFile.write("\n")
	#wekaFile.write("@attribute percentageOfDigits numeric ") 
	#wekaFile.write("\n")
	#wekaFile.write("@attribute percentageOfFullStops numeric ") 
	#wekaFile.write("\n")
	#wekaFile.write("@attribute percentageOfInterjections numeric ") 
	#wekaFile.write("\n")
	#wekaFile.write("@attribute percentageOfModal numeric ") 
	#wekaFile.write("\n")
	#wekaFile.write("@attribute percentageOfNouns numeric ") 
	#wekaFile.write("\n")
	#wekaFile.write("@attribute percentageOfPersonalPronouns numeric ") 
	#wekaFile.write("\n")
	#wekaFile.write("@attribute percentageOfVerbs numeric ") 
	#ekaFile.write("\n")
	wekaFile.write("@attribute class? {18-24, 25-34, 35-49, 50-XX, XX-XX}  ") 
	wekaFile.write("\n")
	wekaFile.write("\n")
	wekaFile.write("@data")
	wekaFile.write("\n")

	f=open(os.path.join("C:/Users/ameer15/python-code/working-function",File+".txt"),'r')
	text=f.read()
	lines=text.split()

	for line in lines:
		w=line.split(',')
		#for i in range(0,29):
			#wekaFile.write(str(w[i]))
			#wekaFile.write(",")
		wekaFile.write(str(w[3]))
		wekaFile.write(",")
		wekaFile.write(str(w[4]))
		wekaFile.write(",")
		wekaFile.write(str(w[5]))
		wekaFile.write(",")
		wekaFile.write(str(w[6]))
		wekaFile.write(",")
		wekaFile.write("?")
		#wekaFile.write(str(w[30]))
		wekaFile.write("\n")                 
  
	wekaFile.close()
	f.close()
  
  





      